{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.remi-quinto",
    "module": "test-jitpack-aar2",
    "version": "0.2.32",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-jitpack-aar2-0.2.32.aar",
          "url": "test-jitpack-aar2-0.2.32.aar",
          "size": 2548,
          "sha512": "84411cae257e2ae0def61cd7abf52b1957434f207d7bd215c05727c3e0c8afff2c164ea282322e25bd830d2bd621342017ad4250bd96e35187ebef94270b0131",
          "sha256": "a373b11350914b97cd12ebe29b6aa828474b53b1ad94a83338743c8fa0bba8bf",
          "sha1": "d27818d384359ff80fdc080b7ee43c0850b6d4be",
          "md5": "597e11026d9f1c8a0e72d0d3a7678015"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-jitpack-aar2-0.2.32.aar",
          "url": "test-jitpack-aar2-0.2.32.aar",
          "size": 2548,
          "sha512": "84411cae257e2ae0def61cd7abf52b1957434f207d7bd215c05727c3e0c8afff2c164ea282322e25bd830d2bd621342017ad4250bd96e35187ebef94270b0131",
          "sha256": "a373b11350914b97cd12ebe29b6aa828474b53b1ad94a83338743c8fa0bba8bf",
          "sha1": "d27818d384359ff80fdc080b7ee43c0850b6d4be",
          "md5": "597e11026d9f1c8a0e72d0d3a7678015"
        }
      ]
    }
  ]
}
