{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.remi-quinto",
    "module": "test-jitpack-aar2",
    "version": "0.2.28",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "test-jitpack-aar2-0.2.28.aar",
          "url": "test-jitpack-aar2-0.2.28.aar",
          "size": 2450,
          "sha512": "f86cd34e690c99799ddec4aff8f641e33becd855a3dba5bc92ee796c54585cab2655f4592a2c3b98547dacbeb307db1ad8a02329ac3059cc39116442bd1b62f5",
          "sha256": "2ccde3765b229da137dd9202f40c1d2d3bb3edba76d162f8793e053dc300a651",
          "sha1": "af04fae171bf1d7dae973995a605fd09620f46ff",
          "md5": "1b43169497fab35db750fc71d2b3c2a9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "test-jitpack-aar2-0.2.28.aar",
          "url": "test-jitpack-aar2-0.2.28.aar",
          "size": 2450,
          "sha512": "f86cd34e690c99799ddec4aff8f641e33becd855a3dba5bc92ee796c54585cab2655f4592a2c3b98547dacbeb307db1ad8a02329ac3059cc39116442bd1b62f5",
          "sha256": "2ccde3765b229da137dd9202f40c1d2d3bb3edba76d162f8793e053dc300a651",
          "sha1": "af04fae171bf1d7dae973995a605fd09620f46ff",
          "md5": "1b43169497fab35db750fc71d2b3c2a9"
        }
      ]
    }
  ]
}
